
Category.create(name: 'Standard')
Category.create(name: 'Swing')
Category.create(name: 'Ballad')
Category.create(name: 'LatinJazz')
Category.create(name: 'Funk')
Category.create(name: 'JazzFunk')
Category.create(name: 'JazzWaltz')
Category.create(name: 'R&B')

Category.create(name: 'Salsa')
Category.create(name: 'Bachata')
Category.create(name: 'Merengue')
Category.create(name: 'Bolero')
Category.create(name: 'ChaCha')
Category.create(name: 'Cumbia')
Category.create(name: 'Samba')
Category.create(name: 'BossaNova')

Category.create(name: 'Broadway')
Category.create(name: 'Movie')
Category.create(name: 'Pop50s')
Category.create(name: 'Pop60s')
Category.create(name: 'Pop70s')
Category.create(name: 'Pop80s')
Category.create(name: 'Pop90s')
Category.create(name: 'Pop00s')
Category.create(name: 'Pop10s')

Song.create(title: 'Blue Skies')
Song.create(title: 'Llororas')
Song.create(title: 'El Cantante')
Song.create(title: 'Vamonos Pal Monte')
Song.create(title: 'Satin Doll')
Song.create(title: 'Mr. Magic')
Song.create(title: "Well You Need'nt")
Song.create(title: 'The Chicken')

SongCategory.create(song_id: 1, category_id: 1)
SongCategory.create(song_id: 2, category_id: 6)
SongCategory.create(song_id: 3, category_id: 6)
SongCategory.create(song_id: 4, category_id: 6)
SongCategory.create(song_id: 5, category_id: 1)
SongCategory.create(song_id: 6, category_id: 4)
SongCategory.create(song_id: 6, category_id: 6)
SongCategory.create(song_id: 7, category_id: 6)
SongCategory.create(song_id: 8, category_id: 6)

Resource.create(name: 'RealBook1.pdf', format: 'pdf-book', description: 'Real Book 1 pdf', location: 'resources/books folder')
Resource.create(name: 'RealBook2.pdf', format: 'pdf-book', description: 'Real Book 2 pdf', location: 'resources/books folder')
Resource.create(name: 'RealBook3.pdf', format: 'pdf-book', description: 'Real Book 3 pdf', location: 'resources/books folder')
Resource.create(name: 'RealBook6.pdf', format: 'pdf-book', description: 'Real Book 6 pdf', location: 'resources/books folder')

Resource.create(song_id: 2, name: 'blue-skies.sib', format: 'sib', description: 'sib file', location: 'resources folder')
Resource.create(song_id: 2, name: 'blue-skies.mp3', format: 'mp3', description: 'mp3 audio file', location: 'resources folder')
Resource.create(song_id: 2, name: 'blue-skies-piano.pdf', format: 'pdf', description: 'piano part pdf', location: 'resources folder')
Resource.create(song_id: 2, name: 'blue-skies-horns.pdf', format: 'pdf', description: 'horn part pdf', location: 'resources folder')
Resource.create(song_id: 2, name: 'blue-skies-lyrics.txt', format: 'txt', description: 'lyrics text file', location: 'resources folder')

Resource.create(song_id: 3, name: 'llororas.sib', format: 'sib', description: 'sib file', location: 'resources folder')
Resource.create(song_id: 3, name: 'llororas.mp3', format: 'mp3', description: 'mp3 audio file', location: 'resources folder')
Resource.create(song_id: 3, name: 'llororas-piano.pdf', format: 'pdf', description: 'piano part pdf', location: 'resources folder')
Resource.create(song_id: 3, name: 'llororas-horns.pdf', format: 'pdf', description: 'horn part pdf', location: 'resources folder')
Resource.create(song_id: 3, name: 'llororas-lyrics.txt', format: 'txt', description: 'lyrics text file', location: 'resources folder')

Resource.create(song_id: 4, name: 'el-cantante.sib', format: 'sib', description: 'sib file', location: 'resources folder')
Resource.create(song_id: 4, name: 'el-cantante.mp3', format: 'mp3', description: 'mp3 audio file', location: 'resources folder')
Resource.create(song_id: 4, name: 'el-cantante-piano.pdf', format: 'pdf', description: 'piano part pdf', location: 'resources folder')
Resource.create(song_id: 4, name: 'el-cantante-horns.pdf', format: 'pdf', description: 'horn part pdf', location: 'resources folder')
Resource.create(song_id: 4, name: 'el-cantante-lyrics.txt', format: 'txt', description: 'lyrics text file', location: 'resources folder')

Resource.create(song_id: 5, name: 'vamonos-pal-monte.sib', format: 'sib', description: 'sib file', location: 'resources folder')
Resource.create(song_id: 5, name: 'vamonos-pal-monte.mp3', format: 'mp3', description: 'mp3 audio file', location: 'resources folder')
Resource.create(song_id: 5, name: 'vamonos-pal-monte-piano.pdf', format: 'pdf', description: 'piano part pdf', location: 'resources folder')
Resource.create(song_id: 5, name: 'vamonos-pal-monte-horns.pdf', format: 'pdf', description: 'horn part pdf', location: 'resources folder')
Resource.create(song_id: 5, name: 'vamonos-pal-monte-lyrics.txt', format: 'txt', description: 'lyrics text file', location: 'resources folder')

Resource.create(song_id: 6, name: 'satin-doll.sib', format: 'sib', description: 'sib file', location: 'resources folder')
Resource.create(song_id: 6, name: 'satin-doll.mp3', format: 'mp3', description: 'mp3 audio file', location: 'resources folder')
Resource.create(song_id: 6, name: 'satin-doll-piano.pdf', format: 'pdf', description: 'piano part pdf', location: 'resources folder')
Resource.create(song_id: 6, name: 'satin-doll-horns.pdf', format: 'pdf', description: 'horn part pdf', location: 'resources folder')
Resource.create(song_id: 6, name: 'satin-doll-lyrics.txt', format: 'txt', description: 'lyrics text file', location: 'resources folder')

Resource.create(song_id: 7, name: 'mr-magic.sib', format: 'sib', description: 'sib file', location: 'resources folder')
Resource.create(song_id: 7, name: 'mr-magic.mp3', format: 'mp3', description: 'mp3 audio file', location: 'resources folder')
Resource.create(song_id: 7, name: 'mr-magic-piano.pdf', format: 'pdf', description: 'piano part pdf', location: 'resources folder')
Resource.create(song_id: 7, name: 'mr-magic-horns.pdf', format: 'pdf', description: 'horn part pdf', location: 'resources folder')
Resource.create(song_id: 7, name: 'mr-magic-lyrics.txt', format: 'txt', description: 'lyrics text file', location: 'resources folder')

Resource.create(song_id: 8, name: 'well-you-neednt.sib', format: 'sib', description: 'sib file', location: 'resources folder')
Resource.create(song_id: 8, name: 'well-you-neednt.mp3', format: 'mp3', description: 'mp3 audio file', location: 'resources folder')
Resource.create(song_id: 8, name: 'well-you-neednt-piano.pdf', format: 'pdf', description: 'piano part pdf', location: 'resources folder')
Resource.create(song_id: 8, name: 'well-you-neednt-horns.pdf', format: 'pdf', description: 'horn part pdf', location: 'resources folder')
Resource.create(song_id: 8, name: 'well-you-neednt-lyrics.txt', format: 'txt', description: 'lyrics text file', location: 'resources folder')

Resource.create(song_id: 9, name: 'the-chicken.sib', format: 'sib', description: 'sib file', location: 'resources folder')
Resource.create(song_id: 9, name: 'the-chicken.mp3', format: 'mp3', description: 'mp3 audio file', location: 'resources folder')
Resource.create(song_id: 9, name: 'the-chicken-piano.pdf', format: 'pdf', description: 'piano part pdf', location: 'resources folder')
Resource.create(song_id: 9, name: 'the-chicken-horns.pdf', format: 'pdf', description: 'horn part pdf', location: 'resources folder')
Resource.create(song_id: 9, name: 'the-chicken-lyrics.txt', format: 'txt', description: 'lyrics text file', location: 'resources folder')

Collection.create(name: 'salsa gig')
SongCollection.create(collection_id: 1, song_id: 2)
SongCollection.create(collection_id: 1, song_id: 3)
SongCollection.create(collection_id: 1, song_id: 4)

Collection.create(name: 'swing gig')
SongCollection.create(collection_id: 2, song_id: 1)
SongCollection.create(collection_id: 2, song_id: 5)

Collection.create(name: 'jazz funk gig')
SongCollection.create(collection_id: 3, song_id: 6)
SongCollection.create(collection_id: 3, song_id: 7)
SongCollection.create(collection_id: 3, song_id: 8)

Collection.create(name: 'solo piano gig')
SongCollection.create(collection_id: 4, song_id: 1)
SongCollection.create(collection_id: 4, song_id: 2)
SongCollection.create(collection_id: 4, song_id: 3)
SongCollection.create(collection_id: 4, song_id: 4)
SongCollection.create(collection_id: 4, song_id: 5)
SongCollection.create(collection_id: 4, song_id: 6)
SongCollection.create(collection_id: 4, song_id: 7)
SongCollection.create(collection_id: 4, song_id: 8)

Collection.create(name: 'Howard Rubenstein gig')
Collection.create(name: 'Vibra Tropicale gig')
Collection.create(name: 'Afrika Gente gig')
Collection.create(name: 'Sabor Picante gig')
Collection.create(name: 'Quartet gig')